model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]
env = { "MEMORY_FILE_PATH" = "/home/ubuntu/.codex/memory.json"}

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/home/ubuntu/repos/"]

[mcp_servers.serena]
startup_timeout_sec = 60
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex"]

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"

[features]
rmcp_client = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
